services:
  db:
    image: postgres:16
    container_name: bookstore-db
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - bookstore_pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bookstore-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      # IMPORTANT: inside docker-compose network, use service name "db"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  bookstore_pgdata:
