pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
    }

    stage('Test') {
      steps {
        sh 'mvn -B test'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

    stage('Package Artifact') {
      steps {
        sh 'ls -la target || true'
        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
      }
    }

    // Optional: CI check that Dockerfile builds (does NOT push or deploy)
    stage('Docker Build (optional)') {
      steps {
        sh 'docker build -t bookstore-ci:${BUILD_NUMBER} .'
      }
    }
  }
}
